# Generated by Django 3.2.4 on 2021-06-04 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='person_responsible',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
